In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],[4,5,6.5]])

In [5]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype

(dtype('int32'), dtype('float64'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
#Create a Dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2
               )
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [18]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros=np.zeros((2,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array=np.random.randint(0,10,size=(3,5))

In [24]:
random_array

array([[6, 6, 5, 4, 2],
       [2, 2, 0, 6, 0],
       [5, 7, 7, 0, 7]])

In [25]:
random_array_2=np.random.random((2,3))
random_array_2

array([[0.77745962, 0.04434332, 0.19370951],
       [0.41688209, 0.24002474, 0.16512427]])

In [37]:
# Pseudo-random number
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matrices