In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],[4,5,6.5]])

In [5]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [102]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype

(dtype('int32'), dtype('float64'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
#Create a Dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2
               )
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [18]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros=np.zeros((2,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [103]:
range_array=np.arange(0,11,2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [109]:
random_array=np.random.randint(0,11,size=(3,5))

In [110]:
random_array

array([[ 6,  8,  4,  1,  4],
       [ 9, 10, 10,  8,  1],
       [ 1,  7,  9,  9,  3]])

In [104]:
random_array_2=np.random.random((2,3))
random_array_2

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102]])

In [112]:
# Pseudo-random number
np.random.seed(seed=0)
random_array_4=np.random.randint(11,size=(5,3))
random_array_4

array([[ 5,  0,  3],
       [ 3,  7,  9],
       [ 3,  5,  2],
       [ 4,  7,  6],
       [ 8,  8, 10]])

## Viewing arrays and matrices

In [113]:
np.unique(random_array_4)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a1,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3. ],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [40]:
a1[0]

1

In [41]:
a2[0][0]

1.0

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a3[0][0]

array([1, 2, 3])

In [44]:
a3[0][0][1]

2

In [46]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [47]:
a4=np.random.randint(10,size=(2,3,4,5))

In [48]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [114]:
a4[1:,1:2,:1,:]

array([[[[0, 1, 2, 4, 2]]]])

## 4. Manipulating and comparing arrays

### Arithmetic 

In [51]:
a1

array([1, 2, 3])

In [52]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [54]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [55]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [56]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [59]:
#floors down the decimal part(rounds off)
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [58]:
a2**2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [60]:
np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

### Aggregation

Aggregation=performing number of operations on a number of things

In [61]:
listy_list=[1,2,3]
type(listy_list)

list

In [62]:
sum(listy_list)

6

In [63]:
type(a1)

numpy.ndarray

In [64]:
sum(a1)

6

In [65]:
np.sum(a1)

6

In [66]:
massive_array=np.random.random(10000)

In [68]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [69]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

845 µs ± 90.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
8.9 µs ± 583 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [70]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [71]:
np.mean(a2)

3.5833333333333335

In [72]:
np.max(a2)

6.5

In [73]:
np.std(a2)

1.8352262954621035

In [74]:
np.var(a2)

3.368055555555556

## Reshaping and transposing

In [75]:
a2


array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [77]:
a2.shape

(2, 3)

In [118]:
a2_reshape=a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [89]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [91]:
#Transpose- switches the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.5]])

In [92]:
a2.T.shape

(3, 2)

In [93]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [94]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [96]:
#element wise multiplication
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [97]:
mat1T=mat1.T

In [101]:
#dot product
np.dot(mat2,mat1T)

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

## Sorting arrays

In [120]:
random_array

array([[ 6,  8,  4,  1,  4],
       [ 9, 10, 10,  8,  1],
       [ 1,  7,  9,  9,  3]])

In [121]:
np.sort(random_array)

array([[ 1,  4,  4,  6,  8],
       [ 1,  8,  9, 10, 10],
       [ 1,  3,  7,  9,  9]])

In [122]:
np.argsort(random_array)

array([[3, 2, 4, 0, 1],
       [4, 3, 0, 1, 2],
       [0, 4, 1, 2, 3]], dtype=int64)

In [124]:
np.argmin(random_array)

3

## Practical Example

In [ ]:
from matplotlib.image import imread
panda=imread("panda.png")
print(type(panda))


<img src="panda.png"/>

In [129]:
panda[:1]


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [134]:
car=imread("car-photo.png")

In [135]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<img src="car-photo.png"/>

In [137]:
dog=imread("dog-photo.png")

In [138]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [141]:
dog.shape

(432, 575, 4)

In [143]:
dog[:1,:1,:1]

array([[[0.70980394]]], dtype=float32)