In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],[4,5,6.5]])

In [5]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype

(dtype('int32'), dtype('float64'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
#Create a Dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2
               )
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [18]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros=np.zeros((2,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array=np.random.randint(0,10,size=(3,5))

In [24]:
random_array

array([[6, 6, 5, 4, 2],
       [2, 2, 0, 6, 0],
       [5, 7, 7, 0, 7]])

In [25]:
random_array_2=np.random.random((2,3))
random_array_2

array([[0.77745962, 0.04434332, 0.19370951],
       [0.41688209, 0.24002474, 0.16512427]])

In [37]:
# Pseudo-random number
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3. ],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [40]:
a1[0]

1

In [41]:
a2[0][0]

1.0

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a3[0][0]

array([1, 2, 3])

In [44]:
a3[0][0][1]

2

In [46]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [47]:
a4=np.random.randint(10,size=(2,3,4,5))

In [48]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [50]:
a4[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

## 4. Manipulating and comparing arrays

### Arithmetic 

In [51]:
a1

array([1, 2, 3])

In [52]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [54]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [55]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [56]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [59]:
#floors down the decimal part(rounds off)
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [58]:
a2**2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [60]:
np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])